version: '3.8'

services:
  # Votre service PHP existant (gardé identique)
  php-apache:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php-apache
    ports:
      - "8082:80"
    volumes:
      - ./src:/var/www/html/  # Plus spécifique que ./
      - ./data/audio:/var/www/html/temp/audio/
      - ./data/logs:/var/www/html/logs/
    environment:
      - DB_HOST=mysql-db
      - DB_NAME=mydb
      - DB_USER=user
      - DB_PASS=userpassword
    depends_on:
      - mysql-db
      - kokoro-tts  # Nouveau dépendance
    networks:
      - mynetwork

  # NOUVEAU : Service Kokoro TTS
  kokoro-tts:
    build:
      context: ./python
      dockerfile: Dockerfile
    container_name: kokoro-tts
    volumes:
      - ./data/audio:/app/audio/
      - ./data/models:/app/models/
    environment:
      - TRANSFORMERS_CACHE=/app/models
    networks:
      - mynetwork

  # Vos services existants (identiques)
  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpassword
    volumes:
      - mysql-data:/var/lib/mysql
      - ./mydb.sql:/docker-entrypoint-initdb.d/mydb.sql
    networks:
      - mynetwork

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8083:80"
    environment:
      PMA_HOST: mysql-db
      PMA_PORT: 3306
    networks:
      - mynetwork

volumes:
  mysql-data:

networks:
  mynetwork:
    driver: bridge